# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 18:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chatusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.CharField(max_length=100)),
                ('facebook_image', models.ImageField(null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='conversations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('converse', models.CharField(max_length=320)),
                ('facebook_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatusers')),
            ],
        ),
        migrations.CreateModel(
            name='destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('defaultimage', models.ImageField(null=True, upload_to=b'')),
                ('owner', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_services', django.contrib.postgres.fields.jsonb.JSONField()),
                ('destinations_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.destinations')),
            ],
        ),
    ]
