# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-07 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
