# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 18:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversations_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='address',
            field=models.CharField(default='PUP Sta.Mesa', max_length=100),
        ),
        migrations.AddField(
            model_name='destinations',
            name='contact_number',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='destinations',
            name='description',
            field=models.CharField(default='Description', max_length=500),
        ),
        migrations.AddField(
            model_name='destinations',
            name='imageUrls',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{default: none}'),
        ),
        migrations.AddField(
            model_name='destinations',
            name='website',
            field=models.CharField(default='www.taralibot.xyz', max_length=100),
        ),
    ]
