# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-10 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_user_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='image_five',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='destinations',
            name='image_four',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='destinations',
            name='image_one',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='destinations',
            name='image_three',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='destinations',
            name='image_two',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
